//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.ItemEntradas = new HashSet<ItemEntrada>();
        }
    
        public int Id { get; set; }
        public int FornecedorId { get; set; }
        public int ItemEntradaId { get; set; }
        public decimal PrecoTotal { get; set; }
        public System.DateTime Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemEntrada> ItemEntradas { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
