//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelosContainer : DbContext
    {
        public ModelosContainer()
            : base("name=ModelosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<Estoque> Estoques { get; set; }
        public virtual DbSet<ItemEntrada> ItemEntradas { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Fornecedor> Fornecedores { get; set; }
        public virtual DbSet<ItemSaida> ItemSaidas { get; set; }
        public virtual DbSet<Venda> Vendas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Recebimento> Recebimentos { get; set; }
    }
}
