//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaEntrada()
        {
            this.ItemNotaEntrada = new HashSet<ItemNotaEntrada>();
        }
    
        public int Id { get; set; }
        public int Numero { get; set; }
        public System.DateTime DataEntrada { get; set; }
        public System.DateTime DataEmissao { get; set; }
        public decimal ValorTotal { get; set; }
        public int FornecedorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemNotaEntrada> ItemNotaEntrada { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
