//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recebimento
    {
        public int Id { get; set; }
        public System.DateTime DataVendimento { get; set; }
        public decimal Valor { get; set; }
        public int NotaSaidaId { get; set; }
    
        public virtual NotaSaida NotaSaida { get; set; }
    }
}
